// <auto-generated />
namespace Persistanse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Finally : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Finally));
        
        string IMigrationMetadata.Id
        {
            get { return "202212011823099_Finally"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
